### PR TITLE
Add --pre flag for managing pre-release package versions

### PR DESCRIPTION
**Pull request by oyale**
Hello,

I've recently submitted an issue (#67) regarding the addition of a flag to retrieve the latest version of a package, including unstable versions, specifically for packages hosted on PyPI. After discussing the issue, I have implemented the proposed changes and would like to contribute them to the project.

In this pull request, I have:

1. Added the `--include-unstable` flag to the argument parser, which allows users to opt-in to retrieving the latest available package version, even if it is not stable.
2. Updated the `get_latest_version` function to accept an additional parameter, `include_unstable`, and modified the function's behavior to return the latest available version when this flag is set to `True` and the package source is PyPI.
3. Made necessary changes to the main function to pass the `include_unstable` flag from the command line arguments to the `get_latest_version` function.

To retrieve the latest unstable version, we made the following changes to the original code in the `get_latest_version` function:

1. If the flag is enabled, instead of directly fetching the latest stable version from the `info` field in the JSON response, we now fetch the entire `releases` dictionary.
2. ~~We rely on the assumption that the order of the releases in the JSON response is already chronological, so we can avoid using the `LooseVersion` class for sorting. This decision reduces the complexity of dependencies in our script.~~
3. We iterate through the sorted versions in reverse order (starting from the latest) and check the `yanked` attribute for each release file associated with the version.
4. If the `yanked` attribute is set to `false` for at least one release file, we consider the version as the latest available and return it.

I have tested these changes with various packages on PyPI, and the results are as expected. By default, the script continues to return only the latest stable versions, while using the `--include-unstable` flag allows users to retrieve the latest available version, even if it's not stable.

Please review the changes in this pull request and let me know if you have any suggestions, concerns, or questions. I'm more than happy to make any necessary adjustments or provide additional information.

Thank you for considering my contribution!

### CODE REVIEW

**Comment by oyale** [comment]
We have realized that we cannot rely on the order of the releases in the JSON response. As a result, we have ended incorporated the `LooseVersion` dependency to ensure proper sorting of releases. 

This change ensures that our script correctly handles version comparisons and updates regardless of the initial order in the JSON response.

**Comment by oyale** [comment]
This is the output of running the regular command on a file with prerelease versions just after run the command with the new flag:

```terminal
Checking dependencies
100%|████████████████████| 69/69 [00:03<00:00, 17.60it/s]

In requirements.txt

odoo12-addon-l10n-es-aeat         12.0.3.0.0.99.dev1  →  12.0.3.0.0
odoo12-addon-l10n-es-aeat-mod111  12.0.1.4.0.99.dev1  →  12.0.1.4.0
odoo12-addon-l10n-es-aeat-mod115  12.0.1.4.0.99.dev3  →  12.0.1.4.0
odoo12-addon-l10n-es-aeat-mod123  12.0.1.3.0.99.dev2  →  12.0.1.3.0
odoo12-addon-l10n-es-aeat-mod216  12.0.2.4.0.99.dev1  →  12.0.2.4.0
odoo12-addon-l10n-es-aeat-mod296  12.0.2.2.0.99.dev1  →  12.0.2.2.0
odoo12-addon-l10n-es-aeat-mod303  12.0.4.0.0.99.dev1  →  12.0.4.0.0
```

**Comment by oyale** [comment]
Renamed to `--pre` to be aligned with [pip args](https://pip.pypa.io/en/stable/cli/pip_install/#install-pre)

**Comment by zehengl** [comment]
Thanks for the PR!

**Comment by zehengl** [comment]
@all-contributors please add @oyale for code

**Pull request merged**
