### PR TITLE
Add a return code after the checks

### PR DESCRIPTION
**Pull request by atchisson**
Added a simple return code after all the checks, 0 if there is nothing to update, 1 otherwise.

I didn't put it behind a feature flag because I think the impact is minimal, but I can look into adding it if necessary.

### CODE REVIEW

**Comment by zehengl** [comment]
Thanks for the contributing! Can you make it behind a feature flag? This library is used in a GitHub Action (see [here](https://github.com/zehengl/refresh-python-dependency/blob/main/action.yml#L20)). Return code 1 if there's no update would "break" it, I think.

Check out the flags in [\_\_main\_\_.py](https://github.com/zehengl/pip-check-updates/blob/main/src/pip_check_updates/__main__.py#L27C5-L42C25). Looks like we would need to modify args.py and config.py

**Comment by atchisson** [comment]
I'm not sure about the flag name; I'm open to suggestions if you have a better one 😅

**Comment by atchisson** [comment]
maybe it should fail by default in "check mode", and not fail when using the -u option ?

**Comment by zehengl** [comment]
@all-contributors please add @atchisson for code

**Pull request merged**
